FROM opxhub/gbp:%%DEBIAN-DIST%%

# Add any tools required for development
RUN apt-get -qq update && apt-get -qq upgrade -y && apt-get -qq install -y \
    bash-completion \
    vim \
 && apt-get -qq autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir controlgraph

# Launch into an interactive shell
CMD ["bash", "-l"]

# vi:syntax=dockerfile
