steps:
  - label: ":bash: Shellcheck"
    plugins:
      shellcheck#v1.1.1:
        files:
          - .buildkite/publish.bash
          - assets/bash_aliases
          - assets/entrypoint.sh
          - assets/install-build-deps
          - assets/pool-packages
  - label: ":docker: Build Stretch"
    agents:
      queue: "docker"
    env:
      DIST: stretch
    command: |
      echo "--- Building images"
      make "DIST=$DIST"
      ./.buildkite/publish.bash
  - label: ":docker: Build Buster"
    agents:
      queue: "docker"
    env:
      DIST: buster
    command: |
      echo "--- Building images"
      make "DIST=$DIST"
      ./.buildkite/publish.bash
  - label: ":docker: Build Xenial"
    agents:
      queue: "docker"
    env:
      DIST: xenial
    command: |
      echo "--- Building images"
      make "DIST=$DIST"
      ./.buildkite/publish.bash
  - label: ":docker: Build Bionic"
    agents:
      queue: "docker"
    env:
      DIST: bionic
    command: |
      echo "--- Building images"
      make "DIST=$DIST"
      ./.buildkite/publish.bash
