steps:
  - label: ":docker: build"
    command: |
      echo "+++ Building stretch image"
      make DIST=stretch
      echo "--- Building buster image"
      make DIST=buster
  - wait
  - label: ":docker: push"
    branches: "master"
    command: |
      echo "+++ Pushing docker images"
      docker push opxhub/gbp:stretch
      docker push opxhub/gbp:stretch-dev
      docker push opxhub/gbp:buster
      docker push opxhub/gbp:buster-dev
      echo "--- Tagging and pushing Stretch image with git sha"
      docker tag opxhub/gbp:stretch "opxhub/gbp:$(git rev-parse HEAD)-stretch"
      docker push "opxhub/gbp:$(git rev-parse HEAD)-stretch"
      docker tag opxhub/gbp:stretch-dev "opxhub/gbp:$(git rev-parse HEAD)-stretch-dev"
      docker push "opxhub/gbp:$(git rev-parse HEAD)-stretch-dev"
