#!/usr/bin/env bash
set -eo pipefail

[[ $# -gt 0 ]] && cd "$1"

if [[ -n "${EXTRA_SOURCES}" ]]; then
  echo "${EXTRA_SOURCES}" | sudo tee /etc/apt/sources.list.d/extra.list
fi

set -u

echo "deb [trusted=yes] file:///mnt/pool/${DIST}-${ARCH} ./" \
  | sudo tee /etc/apt/sources.list.d/local.list

mkdir -p "/mnt/pool/${DIST}-${ARCH}/"
pushd "/mnt/pool/${DIST}-${ARCH}/" 2>/dev/null
dpkg-scanpackages -m . >Packages
popd 2>/dev/null

sudo apt-get update

mk-build-deps -i -r -s sudo -t "apt-get --no-install-recommends -y" || {
  echo "Error: Failed to install build dependencies from these sources:"
  tail -n +1 /etc/apt/sources.list /etc/apt/sources.list.d/*.list
  exit 1
}
