#!/usr/bin/env bash
set -euo pipefail

if [[ $# -gt 0 ]]; then
  cd "$1"
  NAME="$1"
  shift
else
  NAME="$(basename "$(pwd)")"
fi

gbp buildpackage --git-export-dir="/mnt/pool/${DIST}-${ARCH}/${NAME}" $@
