#!/usr/bin/env bash
set -eo pipefail

# fail fast if possible
if [[ $# -eq 0 ]] && [[ ! -e ./debian/control ]]; then
  echo "./debian/control" does not exist. Nothing to do.
  exit 1
fi
if [[ $# -eq 1 ]] && [[ ! -e $1/debian/control ]]; then
  echo "$1/debian/control" does not exist. Nothing to do.
  exit 1
fi

if [[ -n "${EXTRA_SOURCES}" ]]; then
  echo "${EXTRA_SOURCES}" | sudo tee /etc/apt/sources.list.d/20extra.list >/dev/null
fi

set -u

# Where deb and dsc files are stored (subdirectories supported)
DEBS=/mnt
# Where Packages/Sources/Release files are stored
REPO=/var/lib/mnt-apt-repository
# Add local apt repo to sources list
echo "deb [trusted=yes] file://$REPO ./
deb-src [trusted=yes] file://$REPO ./" \
  | sudo tee /etc/apt/sources.list.d/10local.list >/dev/null
sudo mkdir -p "$REPO"
# Index binary and source packages, create release file
apt-ftparchive packages ../../../$DEBS 2>/dev/null | sudo tee $REPO/Packages >/dev/null
apt-ftparchive sources ../../../$DEBS 2>/dev/null | sudo tee $REPO/Sources >/dev/null
apt-ftparchive release $REPO 2>/dev/null | sudo tee $REPO/Release >/dev/null
sudo apt-get -qq update

# Support any number of arguments
if [[ $# -eq 0 ]]; then
  repos="."
else
  repos="$*"
fi

# Install build dependencies for each repo specified
dep_tool="apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
for repo in $repos; do
  if [[ ! -f "$repo/debian/control" ]]; then
    echo "[Warning] $repo/debian/control does not exist." >&2
    continue
  fi

  pushd "$repo" >/dev/null
  if ! mk-build-deps --install --remove --root-cmd sudo --tool "$dep_tool"; then
    echo "Error: Failed to install $repo build dependencies from:"
    tail -n +1 /etc/apt/sources.list /etc/apt/sources.list.d/*.list
    exit 1
  fi
  popd >/dev/null
done
