#!/usr/bin/env bash
set -eo pipefail

[[ $# -gt 0 ]] && cd "$1"

if [[ -n "${EXTRA_SOURCES}" ]]; then
  echo "${EXTRA_SOURCES}" | sudo tee /etc/apt/sources.list.d/20extra.list
fi

set -u

echo "deb [trusted=yes] file:///mnt/pool/${DIST}-${ARCH} ./" \
  | sudo tee /etc/apt/sources.list.d/10local.list

mkdir -p "/mnt/pool/${DIST}-${ARCH}/"
pushd "/mnt/pool/${DIST}-${ARCH}/" 2>/dev/null
dpkg-scanpackages -m . >Packages
popd 2>/dev/null

sudo apt-get update

dep_tool="apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
mk-build-deps --install --remove --root-cmd sudo --tool "$dep_tool" || {
  echo "Error: Failed to install build dependencies from these sources:"
  tail -n +1 /etc/apt/sources.list /etc/apt/sources.list.d/*.list
  exit 1
}
