#!/usr/bin/env bash
set -euo pipefail
#set -x

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <changes file>..." >&2
  exit 1
fi

pool_packages() {
  changes="$1"
  pkg="${changes%%_*}"
  output="pool/${DIST}-${ARCH}/$pkg"

  if [[ ! -e "$changes"  ]]; then
    echo "Changes file '$changes' not found." >&2
    return
  fi

  mkdir -p "$output"

  awk 'f; /Files:/{f=1}' "$changes" | awk '{print $5}' | while read -r f; do
    mv "$f" "$output/$f"
  done

  buildlog="$(basename "$changes" .changes).build"
  if [[ -f $buildlog ]]; then
    mv "$buildlog" "$output/$buildlog"
  fi

  mv "$changes" "$output/$changes"
}

for change in "$@"; do
  pool_packages "$change"
done
